# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- admin/azure-pipelines

pool:
  vmImage: macOS-11

jobs:
- job: dependencies
  steps:
  - script: |
      sw_vers  
      xcodebuild -version
      ls -n /Applications/ | grep Xcode*
    displayName: 'Check MacOS and Xcode Version'

  - script: |
      pwd 
      ls -la
    displayName: 'Show Workspace'

  - task: Cache@2
    inputs:
      key: '"v12" | "$(Agent.OS)" | "src/xcode/Gemfile.lock"'
      restoreKeys: |
        v12 | "$(Agent.OS)"
        v12
      path: |
        src/xcode/vendor/
        /usr/local/Cellar/
        /usr/local/opt/
        /usr/local/bin/
      cacheHitVar: CACHE_RESTORED

  - script: |
      rm '/usr/local/bin/swiftlint'
      brew bundle
      swiftlint --version
    displayName: 'Brew Bundle'
    condition: ne(variables.CACHE_RESTORED, 'true')

  - script: |
      sudo gem install rake bundler:2.1.4
    displayName: 'Install Bundler'
    condition: ne(variables.CACHE_RESTORED, 'true')

  - script: |
      cd src/xcode && bundle install --path=vendor --jobs=8
    displayName: 'Install Dependencies'
    condition: ne(variables.CACHE_RESTORED, 'true')

  - task: Cache@2
    inputs:
      key: '"v12" | "$(Agent.OS)" | "src/xcode/Gemfile.lock"'
      restoreKeys: |
        v12 | "$(Agent.OS)"
        v12
      path: |
        src/xcode/vendor/
        /usr/local/Cellar/
        /usr/local/opt/
        /usr/local/bin/
      cacheHitVar: CACHE_RESTORED

- job: 'BuildForTesting'
  dependsOn: 'dependencies'
  steps:
  - script: |
      cd src/xcode && bundle exec fastlane build_for_testing
    displayName: 'Build for Testing'

- job: 'Swiftlint'
  dependsOn: 'dependencies'
  steps:
  - script: |
      swiftlint --version
      pwd
      ls -la
      cd src/xcode
      ls -la    
      bundle exec fastlane lint
    displayName: 'SwiftLint'

- job: 'RunAllTests'
  dependsOn: 'dependencies'
  steps:
  - script: |
      pwd
      ls -la
      cd src/xcode
      ls -la
      bundle exec fastlane test_without_building testplan:AllTests
    displayName: 'Run AllTests'