# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  name: "Mobile PE"

variables:
  - name: repositoryName
    value: "cwa-app-ios"
  - name: templateName
    value: "templates/ios/stages/"

  - group: "HYPERSPACE_iOS_ENTERPRISE_PIPELINES"

# Define yml templates for specific steps. They are hosted on a external GitHub repsitory.
resources:
  repositories:
    - repository: templates
      type: githubenterprise
      name: SAPMobile/Azure_DevOps_Pipeline_Templates
      endpoint: github.tools.sap

##################################################################################################################################
# This is where the pipeline starts.
##################################################################################################################################
stages:
  - template: ${{ variables.templateName }}build.yml@templates
    parameters:
      stageId: "TestStage"
      stageName: "Test Stage"
      repositoryName: ${{ variables.repositoryName }}
      jobName: "Run UI tests and grab screenshots"
      customLane: "test"
