# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- admin/azure-pipelines

pool:
  vmImage: macOS-11

variables:
  DERIVED_DATA_FOLDER: $(Build.SourcesDirectory)/src/xcode/DerivedData
  TEST_OUTPUT_FOLDER: $(Build.SourcesDirectory)/src/xcode/fastlane/test_output

jobs:

- job: 'BuildForTesting'
  steps:

  - script: |
      cd src/xcode && bundle install --jobs=8
    displayName: 'Install Dependencies'

  - script: |
      cd src/xcode && bundle exec fastlane build_for_testing
    displayName: 'Build for Testing'

  - script: |
      cd $(Build.SourcesDirectory)/src/xcode/fastlane/test_output
      ls -la
      cd $(Build.SourcesDirectory)
    displayName: 'Show test_output folder'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(DERIVED_DATA_FOLDER)
      artifact: 'derivedData'
      publishLocation: 'pipeline'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(TEST_OUTPUT_FOLDER)
      artifact: 'testOutput'
      publishLocation: 'pipeline'

- job: 'testAllTests'
  dependsOn: 'BuildForTesting'
  steps:

  - script: |
      cd src/xcode && bundle install --jobs=8
    displayName: 'Install Dependencies'

  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'test_output'
      targetPath: $(TEST_OUTPUT_FOLDER)

  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'derivedData'
      targetPath: $(DERIVED_DATA_FOLDER)

  - script: |
      cd $(Build.SourcesDirectory)/src/xcode/fastlane/test_output
      ls -la
      cd $(Build.SourcesDirectory)
    displayName: 'Show test_output folder'

  - script: |
      cd src/xcode && bundle exec fastlane test_without_building testplan:AllTests
    displayName: 'test-AllTests'

- job: 'Swiftlint'

  steps:
  - script: |
      cd src/xcode && bundle install --jobs=8
    displayName: 'Install Dependencies'

  - script: |
      cd src/xcode
      bundle exec fastlane lint
    displayName: 'SwiftLint'
