# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- admin/azure-pipelines

pool:
  vmImage: macOS-11

variables:
  SRC_XCODE_FOLDER: $(Build.SourcesDirectory)/src/xcode
  DERIVED_DATA_FOLDER: $(Build.SourcesDirectory)/src/xcode/DerivedData
  TEST_OUTPUT_FOLDER: $(Build.SourcesDirectory)/src/xcode/fastlane/test_output

jobs:

- job: 'BuildForTesting'
  steps:

  - script: |
      cd src/xcode && bundle install --jobs=8
    displayName: 'Install Dependencies'

  - script: |
      cd src/xcode && bundle exec fastlane build_for_testing
    displayName: 'Build for Testing'

  - script: |
      cd $(Build.SourcesDirectory)/src/xcode/fastlane/test_output
      ls -la
      cd $(Build.SourcesDirectory)
    displayName: 'Show test_output folder'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(DERIVED_DATA_FOLDER)'
      includeRootFolder: true
      archiveType: 'tar'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-DerivedData.tgz'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-DerivedData.tgz'
      artifact: 'derivedData'
      publishLocation: 'pipeline'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(TEST_OUTPUT_FOLDER)
      artifact: 'testOutput'
      publishLocation: 'pipeline'

- job: 'testAllTests'
  dependsOn: 'BuildForTesting'
  steps:

  - script: |
      cd src/xcode && bundle install --jobs=8
    displayName: 'Install Dependencies'

  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'testOutput'
      targetPath: $(TEST_OUTPUT_FOLDER)

  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'derivedData'
      targetPath: $(SRC_XCODE_FOLDER)

  - script: |
      cd $(Build.SourcesDirectory)/src/xcode
      ls -la
      cd $(Build.SourcesDirectory)
    displayName: 'Show DerivedData folder'

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(Build.SourcesDirectory)/src/xcode/$(Build.BuildId)-DerivedData.tgz'
      destinationFolder: '$(Build.SourcesDirectory)/src/xcode'
      cleanDestinationFolder: false
      overwriteExistingFiles: true

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 
      Contents: '$(Build.SourcesDirectory)/src/xcode/$(Build.BuildId)-DerivedData.tgz'
      RemoveDotFiles: true

  - script: |
      cd $(Build.SourcesDirectory)/src/xcode
      ls -la
      cd $(Build.SourcesDirectory)/src/xcode/DerivedData
      ls -la
      cd $(Build.SourcesDirectory)
    displayName: 'Show DerivedData folder'

  - script: |
      cd $(Build.SourcesDirectory)/src/xcode/fastlane/test_output
      ls -la
      cd $(Build.SourcesDirectory)
    displayName: 'Show test_output folder'

  - script: |
      cd src/xcode && bundle exec fastlane test_without_building testplan:AllTests
    displayName: 'test-AllTests'

- job: 'Swiftlint'

  steps:
  - script: |
      cd src/xcode && bundle install --jobs=8
    displayName: 'Install Dependencies'

  - script: |
      cd src/xcode
      bundle exec fastlane lint
    displayName: 'SwiftLint'
