# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- admin/azure-pipelines

pool:
  vmImage: macOS-11

variables:
  GEMS_CACHE_FOLDER: /usr/local/lib/ruby/gems

jobs:
- job: dependencies
  steps:
  - script: |
      sw_vers  
      xcodebuild -version
      ls -n /Applications/ | grep Xcode*
    displayName: 'Check MacOS and Xcode Version'

  - script: |
      pwd 
      ls -la
      cd src/xcode
      ls -la
    displayName: 'Show Workspace'

#  - task: Cache@2
#    displayName: 'Restore Gems Cache'
#   inputs:
#      key: 'v1 | gems_cache | "$(Agent.OS)" | $(Build.SourcesDirectory)/src/xcode/Gemfile.lock'
#     restoreKeys: |
#        v1 | gems_cache | "$(Agent.OS)"
#        v1 | gems_cache
#      path: $(GEMS_CACHE_FOLDER)
#      cacheHitVar: GEMS_CACHE_RESTORED

#  - script: |
#      echo GEMS_CACHE_RESTORED: $(VENDOR_CACHE_RESTORED)
#    displayName: 'Check Result of Restoring Caches'

  - script: |
      cd src/xcode && bundle install --jobs=8
    displayName: 'Install Dependencies'

  - script: |
      pwd 
      ls -la
      cd src/xcode
      ls -la
    displayName: 'Show Workspace'

  - script: |
      cd src/xcode
      bundle info fastlane
      bundle info xcode-install
      bundle info fastlane-plugin-appcenter
    displayName: 'Where are dependencies installed?'

  - task: Cache@2
    displayName: 'Store Gems Cache'
    inputs:
      key: 'v1 | gems_cache | "$(Agent.OS)" | $(Build.SourcesDirectory)/src/xcode/Gemfile.lock'
      restoreKeys: |
        v1 | gems_cache | "$(Agent.OS)"
        v1 | gems_cache
      path: $(GEMS_CACHE_FOLDER)

- job: 'BuildForTesting'
  dependsOn: 'dependencies'
  steps:

  - script: |
      pwd 
      ls -la
      cd src/xcode
      ls -la
    displayName: 'Show Workspace'

  - task: Cache@2
    displayName: 'Restore Gems Cache'
    inputs:
      key: 'v1 | gems_cache | "$(Agent.OS)" | $(Build.SourcesDirectory)/src/xcode/Gemfile.lock'
      restoreKeys: |
        v1 | gems_cache | "$(Agent.OS)"
        v1 | gems_cache
      path: $(GEMS_CACHE_FOLDER)
      cacheHitVar: GEMS_CACHE_RESTORED

  - script: |
      echo GEMS_CACHE_RESTORED: $(VENDOR_CACHE_RESTORED)
    displayName: 'Check Result of Restoring Caches'

  - script: |
      cd src/xcode && bundle exec fastlane build_for_testing
    displayName: 'Build for Testing'

- job: 'Swiftlint'
  dependsOn: 'dependencies'
  steps:
  - script: |
      swiftlint --version
      pwd
      ls -la
      cd src/xcode
      ls -la    
      bundle exec fastlane lint
    displayName: 'SwiftLint'
