# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- admin/azure-pipelines

pool:
  vmImage: macOS-11

jobs:
- job: dependencies
  steps:
  - script: |
      sw_vers  
      xcodebuild -version
      ls -n /Applications/ | grep Xcode*
    displayName: 'Check MacOS and Xcode Version'

  - script: |
      pwd 
      ls -la
      cd src/xcode
      ls -la
    displayName: 'Show Workspace'

  - script: |
      cd src/xcode && bundle install --jobs=8
    displayName: 'Install Dependencies'

- job: 'BuildForTesting'
  dependsOn: 'dependencies'
  steps:

  - script: |
      cd src/xcode && bundle install --jobs=8
    displayName: 'Install Dependencies'

  - script: |
      cd src/xcode && bundle exec fastlane build_for_testing
    displayName: 'Build for Testing'

- job: 'Swiftlint'
  dependsOn: 'dependencies'

  - script: |
      cd src/xcode && bundle install --jobs=8
    displayName: 'Install Dependencies'

  steps:
  - script: |
      swiftlint --version
      pwd
      ls -la
      cd src/xcode
      ls -la    
      bundle exec fastlane lint
    displayName: 'SwiftLint'
