# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- admin/azure-pipelines

pool:
  vmImage: macOS-11

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    sw_vers  
    xcodebuild -version
    ls -n /Applications/ | grep Xcode*
  displayName: 'Check MacOS and Xcode Version'

- script: |
    pwd 
    ls -la
  displayName: 'Show Workspace'

- script: |
    rm '/usr/local/bin/swiftlint'
    brew bundle
    swiftlint --version
  displayName: 'Brew Bundle'

- script: |
    sudo gem install rake bundler:2.1.4
  displayName: 'Install Bundler'

- script: |
    cd src/xcode && bundle install --path=vendor --jobs=8
  displayName: 'Install Dependencies'

- script: 
    cd src/xcode && bundle exec fastlane build_for_testing
  displayName: 'Build for Testing'