name: Build on macOS
on:
  push:
    branches:
      - admin/ci-cd-pipelines

jobs:
  dependencies:
    runs-on: macos-11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check MacOS and xCode version
        run: |
          sw_vers  
          xcodebuild -version
          ls -n /Applications/ | grep Xcode*
      - name: Select Xcode 13.1
        run: |
           sudo xcode-select --switch /Applications/Xcode_13.1.app
           xcodebuild -version  
      - name: Brew bundle
        run: |
           rm '/usr/local/bin/swiftlint'
           brew bundle
      - name: Install Bundler
        run: sudo gem install rake bundler:2.1.4 
      - name: Install dependencies
        run: cd src/xcode && bundle install --path=vendor --jobs=8
      - name: Show Workspace
        run: |
          pwd
          ls -la
      - name: save workspace
        uses: actions/cache@v2
        env:
          cache-name: cache-workspace
        with:
          path: |
            - /Users/runner/work/cwa-app-ios/cwa-app-ios/
          key: ${{ runner.os }}-${{ env.cache-name }}-$GITHUB_SHA
      - name: save dependencies and tools cache
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies-and-tools
        with:
          path: |
            - /usr/local/Cellar/
            - /usr/local/opt/
            - /usr/local/bin/
            - /Users/distiller/Library/Caches/Homebrew
            - /usr/local/Homebrew
            - /Users/distiller/.rubies/ruby-*/bin/
          key: ${{ runner.os }}-${{ env.cache-name }}-$GITHUB_SHA
  build:
    runs-on: macos-11
    needs: [dependencies]
    steps:
      - name: Check MacOS and xCode version
        run: |
          sw_vers  
          xcodebuild -version
          ls -n /Applications/ | grep Xcode*
      - name: Select Xcode 13.1
        run: |
           sudo xcode-select --switch /Applications/Xcode_13.1.app
           xcodebuild -version 
      - name: restore workspace
        uses: actions/cache@v2
        env:
          cache-name: cache-workspace
        with:
          path: |
            - /Users/runner/work/cwa-app-ios/cwa-app-ios/
          key: ${{ runner.os }}-${{ env.cache-name }}-$GITHUB_SHA
      - name: restore dependencies and tools cache
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies-and-tools
        with:
          path: |
            - /usr/local/Cellar/
            - /usr/local/opt/
            - /usr/local/bin/
            - /Users/distiller/Library/Caches/Homebrew
            - /usr/local/Homebrew
            - /Users/distiller/.rubies/ruby-*/bin/
          key: ${{ runner.os }}-${{ env.cache-name }}-$GITHUB_SHA
      - name: Show Workspace
        run: |
          pwd
          ls -la        
  swiftlint:
    runs-on: macos-11
    needs: [dependencies]
    steps:
      - name: Check MacOS and xCode version
        run: |
          sw_vers  
          xcodebuild -version
          ls -n /Applications/ | grep Xcode*
      - name: Select Xcode 13.1
        run: |
           sudo xcode-select --switch /Applications/Xcode_13.1.app
           xcodebuild -version      
      - name: restore workspace
        uses: actions/cache@v2
        env:
          cache-name: cache-workspace
        with:
          path: |
            - /Users/runner/work/cwa-app-ios/cwa-app-ios/
          key: ${{ runner.os }}-${{ env.cache-name }}-$GITHUB_SHA
      - name: restore dependencies and tools cache
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies-and-tools
        with:
          path: |
            - /usr/local/Cellar/
            - /usr/local/opt/
            - /usr/local/bin/
            - /Users/distiller/Library/Caches/Homebrew
            - /usr/local/Homebrew
            - /Users/distiller/.rubies/ruby-*/bin/
          key: ${{ runner.os }}-${{ env.cache-name }}-$GITHUB_SHA
      - name: Show Workspace
        run: |
          pwd
          ls -la             
    
