name: Build on macOS
on:
  push:
    branches:
      - admin/ci-cd-pipelines

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check xCode version
        run: |
          xcodebuild -version
