name: Build on macOS
on:
  push:
    branches:
      - admin/ci-cd-pipelines

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check MacOS and xCode version
        run: |
          sw_vers  
          xcodebuild -version
          ls -n /Applications/ | grep Xcode*
      - name: Select Xcode 13.1
        run: |
           sudo xcode-select --switch /Applications/Xcode_13.1.app
           xcodebuild -version  
      - name: Brew bundle
        run: |
           rm '/usr/local/bin/swiftlint'
           brew bundle
      - name: Install Bundler
        run: sudo gem install rake bundler:2.1.4 
      - name: Install dependencies
        run: cd src/xcode && bundle install --path=vendor --jobs=8
      - name: Build for testing
        run: |
          cd src/xcode && bundle exec fastlane build_for_testing
