name: Build on macOS
on:
  push:
    branches:
      - admin/ci-cd-pipelines

jobs:
  buildForTesting:
    runs-on: macos-11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check MacOS and xCode version
        run: |
          sw_vers  
          xcodebuild -version
          ls -n /Applications/ | grep Xcode*
      - name: Select Xcode 13.1
        run: |
           sudo xcode-select --switch /Applications/Xcode_13.1.app
           xcodebuild -version            
      - name: Install dependencies
        run: cd src/xcode && bundle install --jobs=8
      - name: Show where dependencies are installed
        run: |
          cd src/xcode
          bundle info fastlane
          bundle info fastlane-plugin-appcenter
          bundle info xcov
      - name: Build for testing
        run: |
          cd src/xcode && bundle exec fastlane build_for_testing        

          
